version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "23186:3000"
    environment:
      API_PORT: 23186
    volumes:
      - ./api:/src
    depends_on:
      - db
    #   - cache
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: base
    ports:
      - 8085:5432
    volumes:
      - ./dvdrental:/app/data/dvdrental
