version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: celestia-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_PORT: 3000
    volumes:
      - ./api:/src:/express-api
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: celestia-postgres
    restart: always
    environment:
      POSTGRES_USER: celestia-admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: celestia-db
    ports:
      - "8085:5432"
    volumes:
      - ./db/netflix.sql:/docker-entrypoint-initdb.d/netflix.sql
