version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_PORT: 3000
    volumes:
      - ./api:/src
    # depends_on:
    #   - db
    #   - cache
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  # cache:
  #   image: redis:6
  